--CREATE PROCEDURE TOPLAM
--@X1 INT,
--@X2 INT
--AS
--BEGIN
--	SELECT (@X1 + @X2) AS TOPLAM
--END
EXEC TOPLAM 12,41

--CREATE PROCEDURE GOSTER
--@Y1 INT, @Y2 INT
--AS
--BEGIN
--	SELECT (@Y1+@Y2) AS TOPLAM, @Y1,@Y2
--END

EXEC GOSTER 25,54 WITH RESULT SETS((TOPLAM int, Y1 int, Y2 int))
